config/routes.rb
Rails.application.routes.draw do
  resources :users

  get 'home/index'
  get 'home/login'
  get 'home/signup'

  post '/cadastrar' => 'home#create'

  post '/autenticar' => 'sessions#login'
  get '/auth/:provider/callback' => 'sessions#create'
  get '/signout' => 'sessions#destroy', :as => :signout
  get '/signin' => 'sessions#new', :as => :signin

  root :to => 'home#login'

end

app/models/user.rb
class User < ActiveRecord::Base
  def self.create_with_omniauth(auth)
    create! do |user|
      user.provider = auth['provider']
      user.uid = auth['uid']
      if auth['info']
        user.name = auth['info']['name'] || ""
        user.email = auth['info']['email'] || ""
      end
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  private

  helper_method :current_user, :verify_login

  def current_user
  	@current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  
  def verify_login
  	if session[:user_id].nil?
  		redirect_to root_path
  		flash[:alert] = 'Usuário não autenticado.'
  	end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :verify_login, only: [:index]

  # Página principal da aplicação
  def index
    $id_face = session[:token]
    user = User.find_by(:id => session[:user_id])
    $id_user = user.uid
  end

  # Página de login
  def login
  	# Se a seção tiver sido iniciada, o usuário será redirecionado para a página principal
  	if !session[:user_id].nil?
  	  redirect_to controller: 'home', action: 'index'
  	end
  end

  # Página de cadastro
  def signup
  end

  # Função para criar usuário
  def create
  	# Caso o usuário já esteja cadastrado, ele é redirecionado para a página principal
  	user = User.find_by email: params[:email]
  	if user.nil? # Verifica se o resultado da busca é vazio
  	  user = User.new
  	  user.provider = 'aplication' 	# Diferenciação do login do Facebook
  	  user.uid = '000000000000000' 	# Apenas para manter o padrão do usuário do Facebook
  	  user.name = params[:name] 		# Parametro da requisição
  	  user.email = params[:email] 	# Parametro da requisição
  	  user.save						# Cria registro no banco de dados
  	  redirect_to controller: 'home', action: 'index', notice: 'Usuário criado com sucesso'
  	else
  	  redirect_to controller: 'home', action: 'signup', notice: 'Usuário já existe'
  	end 
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  # Função em caso de login pelo facebook
  def create
    auth = request.env["omniauth.auth"]
    user = User.where(:provider => auth['provider'], 
                      :uid => auth['uid']).first || User.create_with_omniauth(auth)
    session[:user_id] = user.id
    session[:token] = auth['credentials']['token']
    redirect_to controller: "home", action: "index", notice: "Usuário autenticado"
  end

  # Função em caso de login nativo
  def login
    user = User.find_by email: params[:email] #, password: params[:password]
    if user
      session[:user_id] = user.id
      redirect_to controller: "home", action: "index", notice: 'Usuário autenticado.'
    else
      redirect_to root_url
      flash[:alert] = 'Matrícula ou senha inválidos'
    end
  end

  def new
    redirect_to '/auth/facebook'
  end

  # Função para destruir sessão
  def destroy
  	session[:user_id] =  nil
  	redirect_to root_url, :notice => 'Signed out'
    
    # Em teste, funcionalidade relacionada ao logout do facebook
    # url = 'https://www.facebook.com/logout.php?next=http://localhost:3000/&access_token='
    # url << session[:token]
    # session[:user_id] = nil
    # session[:token] = nil
    # redirect_to (url)
    # redirect_to ("https://www.facebook.com/logout.php", { :next => "http://localhost:3000/" , :access_token => session[:token] } 
    # redirect_to "https://www.facebook.com/logout.php?next=http://localhost:3000/&access_token=#{session[:token}"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:provider, :uid, :name, :email)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/index.html.erb
<h1>Homepage</h1>
<%= $id_face %> <br>
<%= $id_user %> <br>

<% if current_user %>
	Logado como <strong><%= current_user.name %></strong>
	<%= link_to "Sign Out", signout_path %>
<% else %>
	<%= link_to "Sign in with Facebook OK", "/auth/facebook", id: "sign_in" %>
<% end %>

<!--
<%= link_to 'Enviar notifição', '#', :onclick => "notificar()" %> -->

<a href="https://graph.facebook.com/376068195887486/notifications?access_token=CAAI7a7q9n9MBABuYeM8kARvbBQ2Rh3kixRdpye9Suod0I7IvYo9UohpEqeHMchOyblZADblV07nZAmU98h4gAVfZALqIrbmJZAlFbpsrIpQElNcZCyIOMq1UbSlyqXM0zYVsE61XCcVxP9ZBWF3zGDf8enD9qb9ZCZCRUrjzUejhL93gZClL4O3JKkg4kQNsN4EaOmyUvZAX2KTK1eXerbFxSy&template=Ok">Aqui</a>

app/views/home/login.html.erb
<h1>Manifeste!</h1>

<!-- Formulário de login -->

<%= form_tag autenticar_path do %>
	<div>
	   	<%= label_tag 'email', 'Email' %><br>
	    <%= email_field_tag 'email' %>
	</div>
	<div>
	   	<%= label_tag 'password', 'Senha' %><br>
	  	<%= password_field_tag 'password' %>
	</div>
	<div>
	  	<%= submit_tag 'Entrar' %>
	</div>
<% end %>


<!-- Botões de cadastro -->

<%= link_to 'Cadastre-se', controller:'home', action: 'signup' %>
<%= link_to 'Login com Facebook', "/auth/facebook", id: "sign_in" %>

app/views/home/signup.html.erb
<h1>Cadastro</h1>

<!-- Formulário de cadastro -->

<%= form_tag cadastrar_path do %>
	<div>
	   	<%= label_tag 'name', 'Nome' %><br>
	    <%= text_field_tag 'name' %>
	</div>
	<div>
	   	<%= label_tag 'email', 'Email' %><br>
	    <%= email_field_tag 'email' %>
	</div>
	<!-- Adicionar parametro no banco de dados -- >
	<!--
	<div>
	   	<%= label_tag 'password', 'Senha' %><br>
	  	<%= password_field_tag 'password' %>
	</div>
	-->
	<div>
	  	<%= submit_tag 'Cadastrar' %>
	</div>
<% end %>

<!-- Voltar para a página de login -->
<%= link_to 'Voltar' ,root_url %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
	  <title>Manifeste</title>
	  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
	  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
	  <%= csrf_meta_tags %>
	</head>
	<body>
		<%= yield %>
	</body>
</html>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :provider %><br>
    <%= f.text_field :provider %>
  </div>
  <div class="field">
    <%= f.label :uid %><br>
    <%= f.text_field :uid %>
  </div>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <thead>
    <tr>
      <th>Provider</th>
      <th>Uid</th>
      <th>Name</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.provider %></td>
        <td><%= user.uid %></td>
        <td><%= user.name %></td>
        <td><%= user.email %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Provider:</strong>
  <%= @user.provider %>
</p>

<p>
  <strong>Uid:</strong>
  <%= @user.uid %>
</p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>